-- How the tab bar looks and works.
-- TODO:
-- 1. Show icons on modified buffer.
-- FIXME:
-- 1. gt - dosent switch all the tabs anymore.
-- return {
-- 	"akinsho/bufferline.nvim",
-- 	version = "*",
-- 	dependencies = "nvim-tree/nvim-web-devicons",
-- 	config = function()
-- 		vim.opt.termguicolors = true
-- 		require("bufferline").setup({})
-- 	end,
-- }
